name: VLA_J60738-001
description: 当該GitHubプロジェクト用のIssue
title: "[J60738-001タスク]: "
projects: ["IoVPF-MLOps-Team/2"]
type: task
body:
  - type: input
    id: parent_issue
    attributes:
      label: 親Issue
      description: 親となるIssueのURLを入力してください
      placeholder: https://github.com/org/repo/issues/123
    validations:
      required: true
