name: VLA_J60738-001
description: 当該GitHubプロジェクト用のIssue
title: "[J60738-001_タスク]: "
projects: ["IoVPF-MLOps-Team/2"]
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: タスク説明
      description: タスクの説明 (背景, 課題, 解決方策など) を入力してください
      placeholder: タスクの説明を入力してください
    validations:
      required: true